[build]
  publish = "."

[[redirects]]
  from = "/api/v1/kiruna-update-checker/"
  to = "/.netlify/functions/kiruna-update-checker"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/chat/"
  status = 301

[functions]
  directory = ".netlify/functions"

